### ISSUE TITLE
startapp barifac

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/barifac#10]
# Overview 
```bash
django-admin startapp barifac
```
and other setup

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
-

**Comment by kathmandu777** [comment]
名前がbarifacでリポジトリ名と被るのは避けたい。

**Comment by kathmandu777** [comment]
creditscalとか？

**Comment by Chaha1n** [comment]
> creditscalとか？

credical(生死を分けるような)危機の、きわどい かと思った　由来何？

**Comment by kathmandu777** [comment]
credits cal = credits calculation = 単位計算

**Comment by kathmandu777** [comment]
@Chaha1n 
PR出てる場合はPRにコメントしてほしい。issueでのコメントは実装前の設計段階や実装中に使用する感じで。

**Comment by Chaha1n** [comment]
@kathmandu777 了解。気を付けるわ
