### ISSUE TITLE
その uid はアプリの User と紐付いているか

### ISSUE THREAD

**Issue by Dz0526** [youngeek-0410/barifac#121]
# Overview 
- 特定のエンドポイントに GET したときに uid がアプリの User として登録されているかを確認してほしい。ヘッダーか /v1/api/user/{uid} て感じか？
- レスポンスは任せやす。json がいいでし
- お願いしやす

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
-

**Comment by kathmandu777** [comment]
@Dz0526 
closeしてよい?

**Comment by Dz0526** [comment]
@kathmandu777 
そーりー。 Closeしやす
