### ISSUE TITLE
APIのオプションパラメーターを変更

### ISSUE THREAD

**Issue by yuta0709** [youngeek-0410/barifac#122]
# Overview 

# Background of the improvement 

# Requirements 
- [ ] user
- [x] school
- [x] department
- [x] score
- [x] subject
- [x] evaluation
- [x] teacher
- [x] attend_subject
- [x] term
- [ ] 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
-

**Comment by kathmandu777** [comment]
https://stackoverflow.com/questions/11746894/what-is-the-proper-rest-response-code-for-a-valid-request-but-an-empty-data
