### ISSUE TITLE
change health check response format

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/barifac#14]
# Overview 
health checkのレスポンス形式を一般的なものにする

# Background of the improvement 
https://github.com/kathmandu777/barifac/blob/a5d7ca501215147e3742c04719994eaf0ba33386/fastapi/app/routers/monitoring/health.py#L7
/health にアクセスした際に、サーバーが生きていることを証明するレスポンスを返すことが一般的である。しかし、そのレスポンス形式の標準は明確には定まっていない。現在は上記のように`{"status": "OK"}`と返すようにしてある。health checkのレスポンス形式の標準について調べ、その標準にあったレスポンスを返す実装に変更してほしい。（調べた記事のリンクはこのissueに随時貼ること。このissue以外でも参考にした記事などがあればそのリンクをissueのコメントに残すと良い。）

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
-

**Comment by imtkgtr** [comment]
https://qumeru.com/magazine/510
https://gist.github.com/otaon/13fdf5e035c968e240632bee7e952f46
